### ISSUE TITLE
support for ember addon development

### ISSUE THREAD

**Issue by nvdk** [madnificent/ember-mode#11]
it seems currently ember-mode does not support addon development. In addons the paths to look in are different.

eg templates would be in addon/templates, components in addon/components, etc

would it be possible to at least include these directories when searching for a template, component etc?

**Comment by madnificent** [comment]
maybe.  probably.  not sure.  there is currently no annotation for a file to indicate that it is in the addon folder.  you likely want to stay within the addon namespace if you're coming from a file within that space, hence ember-mode should know about it.  will need to study the impact of this in the sources.

ping me

**Comment by madnificent** [comment]
This has been solved with `ember-toggle-addon`.  Please ping if this is not sufficient.
