### ISSUE TITLE
open-template doesn't work from within a component.js file

### ISSUE THREAD

**Issue by vmalloc** [madnificent/ember-mode#12]

**Comment by madnificent** [comment]
Is the project on which you tried this published?  I can't replicate failure here.

**Comment by vmalloc** [comment]
yes - for instance https://github.com/getslash/backslash - from within https://github.com/getslash/backslash/blob/master/webapp/app/components/query-result/component.js

**Comment by vmalloc** [comment]
Also tried setting usePods to true. Same issue.

**Comment by madnificent** [comment]
it did not work initially, however when using the latest ember-mode with `"usePods": true` in `/webapp/.ember-cli`, it did yield the correct template file when calling `M-x ember-open-template`.

Do you have any errors in the `*Messages*` buffer? Do other movement commands work as expected?

**Comment by vmalloc** [comment]
I see these in messages:
```
checking filename app/templates/components/.gitkeep
checking filename app/templates/test-result.hbs
checking filename app/templates/single_error.hbs
checking filename app/templates/session-result.hbs
checking filename app/templates/errors.hbs
checking filename app/templates/error.hbs
```

Other movements work fine - it seems it's only broken for components

**Comment by madnificent** [comment]
That is the output which I see here when PODs are not enabled.  You should be able to override POD detection by using the `.dir-locals.el` trick (check the README for that).  Are you setting "usePods" in the way I indicated above?  The detection is implemented using regexes, so nothing smart is allowed ;-)

**Comment by vmalloc** [comment]
Oh sorry - my bad. I accidentally reverted .ember-cli on one of my changes.

I still have a problem though - my repo uses a mix of pods and regular layout (all models are in `models/` and the templates and controllers are in pods). I think it would be nice for ember-mode to fallback into the opposite option when not finding its target (like when looking for `foo/model.js` and not finding it, fallback to `models/foo.js` and the other way around. What do you think?
