### ISSUE TITLE
Symbol's value as variable is void: found-file

### ISSUE THREAD

**Issue by breyno127** [madnificent/ember-mode#13]
I am running into this error message with almost all commands. The only thing I can seem to get to work is to run the `open-template` command while I am visiting a template file and get a list of all templates. The same applies for model, controllers and components. I installed with `package-install` and here is the pertinent part of my `init.el`

```
;; ember-mode
(add-hook 'js-mode-hook (lambda () (ember-mode t)))
(add-hook 'web-mode-hook (lambda () (ember-mode t)))
(require 'cl)
```
Can anyone provide any guidance on this?

**Comment by madnificent** [comment]
This should be fixed in the last release, made today.  Can you check?

**Comment by breyno127** [comment]
Looks like its working as advertised now. Thank you! This will do wonders for my ember emacs workflow!
