### ISSUE TITLE
Fails to find root directory when Ember app is not in the root of the repository

### ISSUE THREAD

**Issue by iezer** [madnificent/ember-mode#15]
I'm working on an app with a "Monorepo" structure: The api Rails app and frontend Ember app are in the same git repository in different top-level folders. The structure looks like this:

```
repository
-- .git
-- api/   # directory containing rails server
-- front-end/ # directory containing ember app
    -- .ember-cli
    -- app/
    -- etc....
```

`ember-mode` Doesn't work in this setup because it takes `.git` to indicate the root. I propose Changing [this line](https://github.com/madnificent/ember-mode/blob/master/ember-mode.el#L436) To look for `".ember-cli"` instead of ".git".

Please let me know if you think this is a good idea and I'll open a PR.

**Comment by madnificent** [comment]
Hi @iezer I didn't see this pop in.  Looks better to me than using .git.  I don't see any immediate downsides.

Feel free to send a PR.
