### ISSUE TITLE
Support auto-importing of `service`

### ISSUE THREAD

**Issue by vmalloc** [madnificent/ember-mode#17]
Lots of idiomatic ember code snippets use

```javascript
import {inject as service} from '@ember/service';
```
To make injection line more similar to the old inject API. It would be nice for ember-mode to recognize `service` in this context as well

**Comment by madnificent** [comment]
Good idea.  The last commit of ember-mode has support for importing decorators with `C-c c i d`.  When standing on service, that should import the proposed snippet.
