### ISSUE TITLE
The autoimport for the @atrr decorator imports from the wrong location

### ISSUE THREAD

**Issue by abeforgit** [madnificent/ember-mode#18]
Import should be:
```js
import { attr } from '@ember-data/model';
```

but instead ember-mode adds:
```js
import { attr } from '@ember/data';
```

This is on ember octane, with the following versions
```
ember-cli: 3.20.1
ember-data: 3.21.0
```

Can look into this if you'd like me to, but it's not terribly urgent i think

**Comment by rajasegar** [comment]
I think it is not only `attr`, but `belongsTo` and `hasMany` also are imported from `@ember-data/model`
