### ISSUE TITLE
Support for pod structure.

### ISSUE THREAD

**Issue by rlb3** [madnificent/ember-mode#8]
I would be nice to have support for the pod project structure in ember-mode. This would also help with future compatibility with ember-cli. I believe pod structure will be the default in future versions of ember-cli.

**Comment by madnificent** [comment]
Hi rlb3,

We have considered POD support before but did not find a direct need for it in our current projects. Ember-mode alleviates many issues the POD structure solves.  We did not find a solid way to see if the project was built with PODs or not and the format of the POD structure was still evolving.  As time moves on, POD support indeed becomes more and more relevant and we certainly aim to support it in the long run.

Support for using POD structures should not be hard to add at first sight, given that a project is either fully structured with PODs, or fully without them.  Do you know of an easy way to check if the current project is following the POD structure?  That could greatly speed up adoption.  Ideally speaking, we can run the ember and request info about the current project.  Any pointers?

**Comment by rlb3** [comment]
The only way to tell if a project it using pod structure is to look in the .ember-cli file in the root of the project. It contains json for command line switches that should always be applied. For example: 

```json
{
  "disableAnalytics": false,
  "usePods": true
}
```

The problem is that a user can add ```--pod``` to every command they run. It may be easier to have a custom group option that lets the user specify what layout they have.

**Comment by madnificent** [comment]
I don't think either using the hint in the `.ember-cli` file, nor the custom group option are sufficient for all common cases.  I expect at least some users to both have projects in a POD structure and some not in a POD structure.  I'm willing to make an abstraction from projects which are moving towards a POD structure as that seems to be a one-shot operation.

The `.ember-cli` file is optional, that doesn't seem to be an all-round solution.  A group option would change the mode for all your projects, which doesn't sound awesome if you have multiple ember projects.

Perhaps we can specify an overriding variable in `.dir-locals.el`.  In the short term, we will accept the setting of that file.  In the long term, it will serve as an override.  With the following snippet, PODS would be enabled

```elisp
((nil . ((mode . ember)
         (ember-use-pods . t)))
```

We can later on extend this with a system that tries to discover if PODs are enabled or not.  What system would be used in order to figure that out, could be selected in a custom group option.

Does that sound like a sane approach, or am I missing something?

**Comment by jesse-black** [comment]
Yeah, It's sane. I looked into it a while ago and Ember doesn't even know if a file is pod or traditional until it's resolved at runtime in the browser. Anyways if you use autocompletion like ido or helm it is easy enough to browse pod modules. For example you're in `index/controller.js` and you type `C-x C-f t` and by then it has already autocompleted `index/template.hbs` and you press enter.

**Comment by rlb3** [comment]
I would be fine with a ```.dir-locals.el``` based solution.

**Comment by madnificent** [comment]
Experimental support has been added on the devel branch (see commit d09c7909325d17cb5fd678c312da95f1e4d09d88).  Can you try it out and see if it behaves as expected?

**Comment by rlb3** [comment]
I'm going to try it out today.

**Comment by rlb3** [comment]
If you have ```"usePods": true``` in your .ember-cli file and generate a file with --pod it creates the file in the old layout.

```shell
version: 1.13.8
installing route
  create app/routes/users/new.js
  create app/templates/users/new.hbs
updating router
  add route users/new
installing route-test
  create tests/unit/routes/users/new-test.js
```

If I remove the --pod from the command:

```shell
version: 1.13.8
installing route
  create app/users/new/route.js
  create app/users/new/template.hbs
updating router
  add route users/new
installing route-test
  create tests/unit/users/new/route-test.js
```

**Comment by madnificent** [comment]
I suppose this will best be solved when we learn to detect the setting from `.ember-cli`.  We could parse the value and (potentially) support both cases.

Can you temporarily unset `usePods` in `.ember-cli` and see if it behaves as expected in that case?

I feel like it could be a non-feature to supply the `--pod` as default arguments when you have enabled pods in the `.dir-locals.el`, but not in `.ember-cli`.  On the one hand, it could be nice, on the other hand, I doubt the case will occur that often.  Shall we remove the --pod default for the optional argument?

**Comment by rlb3** [comment]
I think it would be good to remove the --pod optional argument. The fact that it uses the original structure if both ```usePods``` is set to true and --pod is given as an argument is too surprising.

**Comment by madnificent** [comment]
@rlb3 The latest commit on devel ce1280a41d098c043fdd29dff659b7ef6940b2d2 does not have `--pod` as a default argument anymore.  It also tries to detect the `usePods` setting from `.ember-cli`.

Can you give the latest devel branch another test run to check if it now behaves as expected?

@jesse-black Are we missing anything else for POD support or can we merge this into master if it is stable?

**Comment by rlb3** [comment]
I've been using the latest commit this week and it has been working great. Thank for taking the time for this.

robert

**Comment by madnificent** [comment]
Grace period over.  I haven't noticed problems either.  Merging.

Thanks for your input.
