### ISSUE TITLE
Symbol's function definition is void: third

### ISSUE THREAD

**Issue by flyrev** [madnificent/ember-mode#9]
Hi

I'm using GNU Emacs 24.5.1 (Mac), and I have the following .emacs:

<pre>
(load "web-mode.el")
(require 'web-mode)

(load "ember-mode.el")
(require 'ember-mode)

(add-to-list 'auto-mode-alist '("\\.phtml\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.tpl\\.php\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.[agj]sp\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.as[cp]x\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.erb\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.mustache\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.djhtml\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.hbs\\'" . web-mode))

(add-hook 'js-mode-hook (lambda () (ember-mode t)))
(add-hook 'web-mode-hook (lambda () (ember-mode t)))
</pre>

Then, when opening a .hbs file and trying to do ember-open-controller, I get
<pre>
Symbol's function definition is void: third
</pre>

The emacs mode is displayed as (Web [EM]).

**Comment by madnificent** [comment]
Looks a lot like we're missing a dependency on Common Lisp support for
Emacs. I think the package is named cl. You can try and see whether
installing that solves your immediate problem. I'll update the dependencies
soon.

**Comment by flyrev** [comment]
Adding

(require 'cl)

seemed to help.

**Comment by madnificent** [comment]
@jesse-black We have a dependency on, and require, `cl-lib`, should that be `cl` instead?

**Comment by jesse-black** [comment]
cl is deprecated because the functions are un-namespaced, cl-lib has the same functions with `cl-` namespace, try changing it to `cl-third`

**Comment by madnificent** [comment]
Should be fixed in the current release.  Can you check, or should I close?

**Comment by flyrev** [comment]
Removed (require 'cl) from my .emacs and downloaded the latest ember-mode.el. No errors. :)

**Comment by madnificent** [comment]
Thank you! Sorry it took so long to make these minor change.
